# Generated by Django 2.1.7 on 2019-03-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='dd.jpg', upload_to='icon'),
            preserve_default=False,
        ),
    ]
