# Generated by Django 2.1.7 on 2019-03-15 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='joke.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='shanghai', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(default='wshu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='123456', max_length=32),
            preserve_default=False,
        ),
    ]
