# Generated by Django 2.1.7 on 2019-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=6)),
                ('tel', models.CharField(max_length=20)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
    ]
