# Generated by Django 2.1.7 on 2019-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190322_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, upload_to='pic', verbose_name='图片'),
        ),
    ]
